### ISSUE TITLE
国名のが記入欄ない。

### ISSUE THREAD

**Issue by Yukixtaira** [ikedaosushi/ambii-interview-sheet#10]
国名の記入欄がない。
<img width="411" alt="スクリーンショット 2019-10-07 11 54 26" src="https://user-images.githubusercontent.com/44222530/66282147-3a0de280-e8f9-11e9-8f9b-9617571f2656.png">

でもダミー情報では見れてる。
<img width="1272" alt="スクリーンショット 2019-10-07 11 58 07" src="https://user-images.githubusercontent.com/44222530/66282283-bdc7cf00-e8f9-11e9-9bb6-8d657c7c090d.png">

**Comment by ikedaosushi** [comment]
対応完了
