### ISSUE TITLE
simple date input

### ISSUE THREAD

**Issue by yujischuster** [ikedaosushi/ambii-interview-sheet#24]
No more complicated date selection
<img width="353" alt="Screen Shot 2019-11-14 at 6 19 30 PM" src="https://user-images.githubusercontent.com/18061174/68843362-5298c600-070b-11ea-979e-35ec6f65f9d4.png">

**Comment by Yukixtaira** [comment]
<img width="746" alt="スクリーンショット 2019-11-21 17 31 07" src="https://user-images.githubusercontent.com/44222530/69320835-453c8800-0c85-11ea-94fa-1936e5039ba0.png">

**Comment by yujischuster** [comment]
Thank you, I just did the part Yuki commented
