### ISSUE TITLE
（個人情報）病名記入時のボタンの追加検討

### ISSUE THREAD

**Issue by Yukixtaira** [ikedaosushi/ambii-interview-sheet#6]
二つ以上ある場合に下に追加できるような＋のボタンが欲しい。
<img width="505" alt="スクリーンショット 2019-10-07 11 49 29" src="https://user-images.githubusercontent.com/44222530/66281952-886eb180-e8f8-11e9-8da2-fbe5d233e35b.png">

**Comment by ikedaosushi** [comment]
これはセコムの電子カルテの仕様次第なので現時点では一旦テキストで書いてもらうのでいい気がする。

**Comment by ikedaosushi** [comment]
これはセコムの電子カルテの仕様次第なので現時点では一旦テキストで書いてもらうのでいい気がする。
