### ISSUE TITLE
薬の名前記入欄がない

### ISSUE THREAD

**Issue by Yukixtaira** [ikedaosushi/ambii-interview-sheet#9]
薬の名前記入欄がない
<img width="343" alt="スクリーンショット 2019-10-07 11 53 26" src="https://user-images.githubusercontent.com/44222530/66282119-1f3b6e00-e8f9-11e9-849e-2fa769be0ca1.png">

でもダミー情報では見れてる。
<img width="1272" alt="スクリーンショット 2019-10-07 11 58 07" src="https://user-images.githubusercontent.com/44222530/66282283-bdc7cf00-e8f9-11e9-9bb6-8d657c7c090d.png">

**Comment by ikedaosushi** [comment]
対応完了
